### ISSUE TITLE
Game Leader board

### ISSUE THREAD

**Issue by gokultp** [gokultp/go-four-in-a-row#24]
**Is your feature request related to a problem? Please describe.**
It should show a leader board of the game. 
**Describe the solution you'd like**
Show the leader board on the right hand-side of arena like X:3, O: 2
**Describe alternatives you've considered**
Or we can show the leaderboard at the end of every game.

**Comment by dskoda1** [comment]
I'll take this one. Will try to set a leaderboard up on the right side, just outside of the arena.

**Comment by dskoda1** [comment]
Can you assign this to me please? I am doing a bit of refactoring to include a "manager" struct which sits above the "game" struct. Currently am trying to get the main rendering loop to go through the manager, which will enable me to have a leaderboard painted outside of the games display. 

Additionally, a manager will enable us to probably select inputs for the game itself, such as switching between modes between games, changing game size up front and between games, etc.
