### ISSUE TITLE
remove vendor folder

### ISSUE THREAD

**Issue by DanielDanteDosSantosViana** [gokultp/go-four-in-a-row#8]
do you using 'dep' with a dependencies manager, so you don't need commit vendor folder, only run command 'dep ensure' .

**Comment by gokultp** [comment]
Are you sure about dep is managing to keep the same version of dependencies.

**Comment by mukeshmk** [comment]
@gokultp I have run the `dep init` command and configured the `Gopkg.toml` file and `Gopkg.lock` file. And I have also added the 'vendor` folder in `.gitignore` so that it won't be tracked by git anymore.
